// Export options for a Project:
//   - exportJSON          (project state, see storage.js)
//   - exportSingleFileJSX (one self-contained .jsx — drop into any React 18+ project)
//   - exportModuleZip     (full puzzle module + README + project.json)

import { compileProject } from './compile.js';
import { computePiecePath } from '../puzzle/geometry.js';
import { makeZip } from './zip.js';

// Vite reads these as raw text at build time so they ship inside the app.
const PUZZLE_SOURCES = import.meta.glob('../puzzle/**/*.{js,jsx,css,md}', {
  query: '?raw',
  import: 'default',
  eager: true,
});

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// Pre-compile a project into renderable pieces with paths baked in. The single
// file emits this snapshot — runtime needs no math.
function snapshot(project) {
  const pieces = compileProject(project);
  const effect = project.edges?.default?.effect ?? 'puzzle';
  const config = project.edges?.default?.config ?? null;
  return pieces.map((p) => ({
    id: p.id,
    x: p.x, y: p.y, w: p.w, h: p.h,
    label: p.label,
    fill: p.fill ?? null,
    content: p.content ?? null,
    d: computePiecePath(p, pieces, effect, config),
  }));
}

// Build a single self-contained .jsx file. No imports beyond React.
function buildSingleFile(project) {
  const data = snapshot(project);
  const minX = Math.min(...data.map((p) => p.x));
  const minY = Math.min(...data.map((p) => p.y));
  const maxX = Math.max(...data.map((p) => p.x + p.w));
  const maxY = Math.max(...data.map((p) => p.y + p.h));
  const PAD = 60;
  const vb = {
    x: minX - PAD,
    y: minY - PAD,
    w: maxX - minX + PAD * 2,
    h: maxY - minY + PAD * 2,
  };

  return `// Generated by Puzzle Studio.
// Drop this file into any React 18+ project and import the default export:
//
//   import PuzzleExport from './${safeName(project.name)}.jsx';
//   <PuzzleExport />
//
// No external dependencies beyond React.

import React from 'react';

const PIECES = ${JSON.stringify(data, null, 2)};
const VIEWBOX = "${vb.x} ${vb.y} ${vb.w} ${vb.h}";
const SIZE = { w: ${vb.w}, h: ${vb.h} };

export default function PuzzleExport({ width = '100%', height = 'auto', style }) {
  return (
    <svg
      viewBox={VIEWBOX}
      width={width}
      height={height}
      preserveAspectRatio="xMidYMid meet"
      xmlns="http://www.w3.org/2000/svg"
      style={{ display: 'block', maxWidth: '100%', ...style }}
    >
      {PIECES.map((p) => (
        <Piece key={p.id} piece={p} />
      ))}
    </svg>
  );
}

function Piece({ piece }) {
  const { id, x, y, w, h, label, fill, content, d } = piece;
  const clipId = 'pcx-' + id.replace(/[^a-zA-Z0-9]/g, '');
  const hasContent = content && (content.text || content.src);
  return (
    <g>
      {hasContent && (
        <defs>
          <clipPath id={clipId}><path d={d} /></clipPath>
        </defs>
      )}
      <path d={d} fill={fill || '#1f1d28'} stroke="#423a4f" strokeWidth={1.5} strokeLinejoin="round" />
      {hasContent ? (
        <g clipPath={\`url(#\${clipId})\`}>
          <Content x={x} y={y} w={w} h={h} content={content} />
        </g>
      ) : (label && (
        <text x={x + w / 2} y={y + h / 2} textAnchor="middle" dominantBaseline="central"
          fill="#9d96a8" fontSize={14} fontFamily="system-ui, sans-serif">
          {label}
        </text>
      ))}
    </g>
  );
}

function Content({ x, y, w, h, content }) {
  if (content.type === 'image' && content.src) {
    const fit = content.fit || 'cover';
    const par = fit === 'cover' ? 'xMidYMid slice'
              : fit === 'contain' ? 'xMidYMid meet'
              : fit === 'fill' ? 'none'
              : 'xMidYMid meet';
    return <image href={content.src} x={x} y={y} width={w} height={h} preserveAspectRatio={par} />;
  }
  const text = content.text || '';
  const fontSize = content.fontSize || Math.min(w, h) / 8;
  const align = content.align || 'center';
  const color = content.color || '#ede8de';
  const fontWeight = content.fontWeight || 500;
  const PAD = 18;
  const charW = fontSize * 0.55;
  const maxChars = Math.max(1, Math.floor((w - PAD * 2) / charW));
  const lines = [];
  for (const para of text.split('\\n')) {
    if (para === '') { lines.push(''); continue; }
    const words = para.split(/\\s+/);
    let line = '';
    for (const word of words) {
      const next = line ? line + ' ' + word : word;
      if (next.length <= maxChars) line = next;
      else { if (line) lines.push(line); line = word.length <= maxChars ? word : word.slice(0, maxChars); }
    }
    if (line) lines.push(line);
  }
  const lineH = fontSize * 1.25;
  const startY = y + h / 2 - (lines.length * lineH) / 2 + lineH * 0.7;
  const tx = align === 'left' ? x + PAD : align === 'right' ? x + w - PAD : x + w / 2;
  const anchor = align === 'left' ? 'start' : align === 'right' ? 'end' : 'middle';
  return (
    <text textAnchor={anchor} fill={color} fontSize={fontSize} fontWeight={fontWeight}
      fontFamily="system-ui, sans-serif">
      {lines.map((line, i) => (
        <tspan key={i} x={tx} y={startY + i * lineH}>{line}</tspan>
      ))}
    </text>
  );
}
`;
}

const SINGLE_FILE_README = (project) => `# ${project.name || 'Puzzle Export'}

Generated by Puzzle Studio. A single self-contained React component you can drop into any React 18+ project.

## Install

Copy \`${safeName(project.name)}.jsx\` into your project. No additional dependencies are required (just React).

## Usage

\`\`\`jsx
import PuzzleExport from './${safeName(project.name)}.jsx';

export default function App() {
  return (
    <div>
      <PuzzleExport width="100%" />
    </div>
  );
}
\`\`\`

## Props

| Prop     | Type      | Default      | Description                          |
| -------- | --------- | ------------ | ------------------------------------ |
| \`width\`  | number/string | \`'100%'\`     | SVG width attribute.                 |
| \`height\` | number/string | \`'auto'\`     | SVG height attribute.                |
| \`style\`  | object    | —            | Inline style applied to the \`<svg>\`. |

## Notes

- The SVG path geometry is precomputed; the runtime does no math.
- Colors and content (text/images) are baked into the file.
- To re-edit, open the original project JSON in Puzzle Studio.
`;

const MODULE_README = (project) => `# Puzzle Studio Export — Module Bundle

This bundle contains everything needed to render and re-edit your puzzle in your own React app.

## Files

\`\`\`
puzzle/                 ← portable rendering module (drop-in)
  PuzzleBoard.jsx       — root SVG component
  PuzzlePiece.jsx       — individual piece
  geometry.js           — pure path math
  effects/              — connector strategies (puzzle, wave, straight)
  index.js              — public API
project.json            — your project data (re-importable into Puzzle Studio)
README.md               — this file
${safeName(project.name)}.jsx       — turn-key wrapper that compiles project.json + renders it
\`\`\`

## Quick start

1. Copy the \`puzzle/\` folder into your project (e.g. \`src/puzzle/\`).
2. Copy \`project.json\` and \`${safeName(project.name)}.jsx\` next to it.
3. Adjust the import path in \`${safeName(project.name)}.jsx\` if needed.
4. Use it:

\`\`\`jsx
import Puzzle from './${safeName(project.name)}.jsx';

export default function App() {
  return <Puzzle />;
}
\`\`\`

## API (puzzle module)

\`\`\`js
import {
  PuzzleBoard,        // <PuzzleBoard pieces={pieces} effect="puzzle" />
  computePiecePath,   // (piece, allPieces, effect, config) → SVG d
  computePieceBbox,   // (piece, allPieces, effect, config) → {minX,minY,maxX,maxY}
  EFFECT_NAMES,       // ['puzzle', 'wave', 'straight']
} from './puzzle';
\`\`\`

The \`puzzle/\` folder has no imports outside itself. It works in any React 18+ project, with no other dependencies.

## Re-editing

Drop \`project.json\` into Puzzle Studio (Landing → Import) to continue editing.
`;

const MODULE_WRAPPER = (project) => `// Convenience wrapper: imports your project data + renders it with the puzzle module.
import React, { useMemo } from 'react';
import { PuzzleBoard } from './puzzle';
import projectData from './project.json';
import { compileProject } from './compileProject.js';

export default function ${pascalCase(project.name) || 'Puzzle'}({ width = '100%' }) {
  const pieces = useMemo(() => compileProject(projectData), []);
  const effect = projectData.edges?.default?.effect ?? 'puzzle';
  const config = projectData.edges?.default?.config;
  return (
    <div style={{ width }}>
      <PuzzleBoard pieces={pieces} effect={effect} effectConfig={config} />
    </div>
  );
}
`;

// We also need a tiny standalone compileProject for the wrapper. We bundle a
// trimmed copy that depends only on grid.js helpers.
const COMPILE_PROJECT_STANDALONE = `// Standalone compileProject — no imports outside this file.
// Builds piece array from a Project { grid, edges, pieceColors, pieceContent }.
function edgeKey(a, b) { return a < b ? a + '||' + b : b + '||' + a; }

function groupBoundsMap(grid) {
  const map = new Map();
  for (let r = 0; r < grid.rows; r++) {
    for (let c = 0; c < grid.cols; c++) {
      const id = grid.groups[r][c];
      const b = map.get(id);
      if (!b) map.set(id, { rMin: r, rMax: r, cMin: c, cMax: c });
      else {
        if (r < b.rMin) b.rMin = r; if (r > b.rMax) b.rMax = r;
        if (c < b.cMin) b.cMin = c; if (c > b.cMax) b.cMax = c;
      }
    }
  }
  return map;
}

export function compileProject(project) {
  const { grid, edges, pieceColors = {}, pieceContent = {} } = project;
  const cellSize = grid.cellSize;
  const bounds = groupBoundsMap(grid);
  const pieces = [];
  for (const [id, b] of bounds) {
    pieces.push({
      id,
      x: b.cMin * cellSize, y: b.rMin * cellSize,
      w: (b.cMax - b.cMin + 1) * cellSize, h: (b.rMax - b.rMin + 1) * cellSize,
      label: id.startsWith('g-') ? '#' + id.slice(2) : id.split('-')[0],
      fill: pieceColors[id],
      content: pieceContent[id],
      sides: {}, edgeEffects: {}, edgeEffectConfigs: {},
    });
  }
  // The full edge resolution lives in the puzzle module; for export we let
  // PuzzleBoard receive these pieces and compute paths from neighbors.
  return pieces;
}
`;

function safeName(name) {
  return (name || 'puzzle').replace(/[^A-Za-z0-9_-]+/g, '-').replace(/^-+|-+$/g, '') || 'puzzle';
}

function pascalCase(name) {
  if (!name) return '';
  return name.replace(/[^A-Za-z0-9]+/g, ' ').trim().split(/\s+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join('');
}

// --- Public API --------------------------------------------------------------

export function exportSingleFileJSX(project) {
  const name = safeName(project.name);
  const jsx = buildSingleFile(project);
  const readme = SINGLE_FILE_README(project);

  // Two files in one ZIP: the .jsx and a README.md.
  const blob = makeZip([
    { name: `${name}.jsx`, content: jsx },
    { name: 'README.md', content: readme },
  ]);
  downloadBlob(blob, `${name}-component.zip`);
}

export function exportModuleZip(project) {
  const name = safeName(project.name);

  // Bundle every file from src/puzzle/ as raw source.
  const files = [];
  for (const [path, source] of Object.entries(PUZZLE_SOURCES)) {
    // path like '../puzzle/foo/bar.js' → 'puzzle/foo/bar.js'
    const rel = path.replace(/^\.\.\//, '');
    if (rel.endsWith('CLAUDE.md')) continue; // omit dev-only docs
    files.push({ name: rel, content: source });
  }

  files.push({ name: 'project.json', content: JSON.stringify(project, null, 2) });
  files.push({ name: `${name}.jsx`, content: MODULE_WRAPPER(project) });
  files.push({ name: 'compileProject.js', content: COMPILE_PROJECT_STANDALONE });
  files.push({ name: 'README.md', content: MODULE_README(project) });

  const blob = makeZip(files);
  downloadBlob(blob, `${name}-module.zip`);
}
